name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build static assets
        run: |
          mkdir -p public/js public/styles
          cp -r src/js/* public/js/ || true
          cp -r src/styles/* public/styles/ || true

      - name: ESLint
        run: npx --yes eslint@8 src/js --max-warnings=0

      - name: Verify files
        run: |
          test -f public/index.html
          test -f public/js/app.js
          test -f public/styles/main.css

      - name: Prettier check
        run: npx --yes prettier --check .
